export const BOSS_CONFIG = {
	ATTACK_RANGE: Infinity,
	SPEED_MULTIPLIER: 0.8,
	
	PROJECTILE: {
		SIZE: 22,
		SPEED: 0.33,
		MAX_DISTANCE: 800,
		COLOR: '#ff0000',
		attack_DURATION: 1000
	},
	
	SPECIAL_ATTACK: {
		INTERVAL: 6000,
		attack_DURATION: 2500,
		EXPLOSION_RADIUS: 300,
		EXPLOSION_DAMAGE_MULTIPLIER: 2,
		SHOCK_ANIMATION_DURATION: 500
	}
};

